# Generated by Django 4.2.21 on 2025-05-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='photo',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='photo',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
