# Generated by Django 4.2.21 on 2025-05-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_certificate_photo_alter_project_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
