# Generated by Django 4.2.21 on 2025-05-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_information_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeactivity',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
