# Generated by Django 4.2.21 on 2025-05-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_typeactivity_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_link', models.TextField(null=True)),
                ('instagram_link', models.TextField(null=True)),
                ('facebook_link', models.TextField(null=True)),
                ('vk_link', models.TextField(null=True)),
            ],
        ),
    ]
