# Generated by Django 4.2.21 on 2025-05-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='repair',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
