# Generated by Django 4.2.21 on 2025-05-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_certificate_photo_alter_project_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='address',
            new_name='title',
        ),
    ]
